### PR TITLE
FAC-215: Add facebook channels module for new endpoint

### PR DESCRIPTION
**Pull request by bw-tom**
Needed for https://github.com/BrandwatchLtd/qa-brandwatch-api/pull/133

### CODE REVIEW

**Comment by bw-tom** [comment]
Rubocop insisted I change I load of files I didn't touch, but 🤷‍♂️

**Comment by bw-tom** [comment]
Hooray! Thanks for the upstream fix, @lgrzybowski !

**Comment by lgrzybowski** [comment]
LGTM :)

**Comment by bw-tom** [comment]
I don't have permission to merge, so I leave that in your hands 🙇

**Comment by lgrzybowski** [comment]
Done :)

**Pull request merged**
